<a href="https://colab.research.google.com/github/Sunrise-08/Localrepo/blob/main/Email_spam_or_not.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the Dependencies**

In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

**Data Collection & Pre-Processing**

In [5]:
#loading the data from csv file to a pandas DataFrame
raw_mail_data=pd.read_csv('/content/mail_data.csv')

In [6]:
#number of rows and columns in the dataset
raw_mail_data.shape

(5572, 2)

In [7]:
#replace the null values with a null string
mail_data=raw_mail_data.where((pd.notnull(raw_mail_data)),'')

In [8]:
#first 5 rows of the dataset
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
mail_data.isnull().sum()

Category    0
Message     0
dtype: int64

**Label Encoding**

In [10]:
#label spam mail as 0 and ham(non-spam) mail as 1
mail_data.loc[mail_data['Category']=='spam','Category']=0
mail_data.loc[mail_data['Category']=='ham','Category']=1

**spam --> 0**

**ham --> 1**

In [11]:
mail_data.head()

  Category                                            Message
0        1  Go until jurong point, crazy.. Available only ...
1        1                      Ok lar... Joking wif u oni...
2        0  Free entry in 2 a wkly comp to win FA Cup fina...
3        1  U dun say so early hor... U c already then say...
4        1  Nah I don't think he goes to usf, he lives aro...

In [12]:
#separating the data as texts and label
X=mail_data['Message']
Y=mail_data['Category']

In [13]:
print(X)
print(Y)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object
0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

**Splitting the data as training data and test data**

In [14]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=3)

In [15]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=3)

In [16]:
print(X.shape,X_train.shape,X_test.shape)

(5572,) (4457,) (1115,)

In [17]:
#transform the text data to feature vectors that can be used as input to the logistic regression
feature_extraction=TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)

X_train_feature=feature_extraction.fit_transform(X_train)
X_test_feature=feature_extraction.transform(X_test)

#convert Y_train and Y_test values as integers
Y_train=Y_train.astype(int)
Y_test=Y_test.astype(int)

In [18]:
print(X_train_feature)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34678 stored elements and shape (4457, 7493)>
  Coords	Values
  (0, 2353)	0.28101404009316056
  (0, 3806)	0.28101404009316056
  (0, 1857)	0.17073786814794129
  (0, 1193)	0.22908400928709988
  (0, 3113)	0.28101404009316056
  (0, 3627)	0.25144905621529934
  (0, 6330)	0.24059246244542992
  (0, 1540)	0.17407870571957915
  (0, 2644)	0.28101404009316056
  (0, 5029)	0.17467075796896542
  (0, 4306)	0.26793132631329497
  (0, 421)	0.25144905621529934
  (0, 4557)	0.28101404009316056
  (0, 6468)	0.26793132631329497
  (0, 1657)	0.28101404009316056
  (0, 0)	0.23628394623676158
  (1, 3982)	0.4167622750027118
  (1, 5911)	0.2761926296686631
  (1, 3941)	0.20702870014136815
  (1, 1969)	0.1749293187718031
  (1, 6553)	0.4722950153731612
  (1, 5947)	0.24356944504246256
  (1, 3948)	0.2761926296686631
  (1, 2113)	0.1985161464110967
  (1, 3828)	0.13684128003316173
  :	:
  (4456, 5091)	0.1743505991070133
  (4456, 7339)	0.13767285254208542
  (4456, 2414)	0.17857780047236718
  (4456, 3262)	0.16745892210920407
  (4456, 7434)	0.1566807006510762
  (4456, 4120)	0.11213756070741854
  (4456, 3147)	0.11213756070741854
  (4456, 5430)	0.2902170940779003
  (4456, 3362)	0.13296028402451
  (4456, 1571)	0.1695693884304312
  (4456, 4975)	0.15534275099802256
  (4456, 1290)	0.1566807006510762
  (4456, 2236)	0.17068883072653956
  (4456, 2690)	0.19758564858135794
  (4456, 4765)	0.1730749026661772
  (4456, 5420)	0.19758564858135794
  (4456, 4878)	0.2137042449780485
  (4456, 5447)	0.2198234053076842
  (4456, 6646)	0.22771237505351186
  (4456, 6568)	0.23883125341667502
  (4456, 2138)	0.23883125341667502
  (4456, 3913)	0.23883125341667502
  (4456, 1186)	0.23883125341667502
  (4456, 877)	0.23883125341667502
  (4456, 7001)	0.23883125341667502

In [19]:
print(X_test_feature)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7823 stored elements and shape (1115, 7493)>
  Coords	Values
  (0, 893)	0.5968846858730686
  (0, 3659)	0.6647095420885805
  (0, 3748)	0.3001788854729708
  (0, 3982)	0.33433894948510406
  (1, 951)	0.40624130642412104
  (1, 3982)	0.2422352863555815
  (1, 4014)	0.4519692232535757
  (1, 4097)	0.25509897344874266
  (1, 6118)	0.4649108105460211
  (1, 6302)	0.4519692232535757
  (1, 7323)	0.29414309688485146
  (2, 726)	0.5784615622424353
  (2, 1511)	0.5054930834063402
  (2, 3302)	0.3286472702750399
  (2, 4290)	0.35146035376046975
  (2, 6707)	0.42228610575263104
  (3, 1403)	0.3190783090518022
  (3, 1535)	0.26860176862876095
  (3, 1628)	0.33607742717641215
  (3, 2121)	0.17912687495989912
  (3, 2613)	0.32672213738283684
  (3, 3101)	0.2806628348811889
  (3, 3170)	0.2806628348811889
  (3, 4856)	0.3481384934288401
  (3, 5424)	0.3651376115534502
  :	:
  (1111, 2767)	0.25490483698848077
  (1111, 5046)	0.39024262697465245
  (1111, 5357)	0.266009764263899
  (1111, 5618)	0.2999597919047991
  (1111, 6977)	0.1742576981016723
  (1111, 7190)	0.3720747354638948
  (1111, 7418)	0.2595045164597774
  (1112, 1869)	0.6693756697064054
  (1112, 3897)	0.5477089193614008
  (1112, 6679)	0.5019473602451435
  (1113, 1401)	0.5750952380611781
  (1113, 1683)	0.2635451401782607
  (1113, 2572)	0.24950459012529605
  (1113, 4055)	0.18267517691320964
  (1113, 4715)	0.2775856902312253
  (1113, 4994)	0.2698586179417211
  (1113, 5428)	0.28754761903058906
  (1113, 5697)	0.18498458298299114
  (1113, 5750)	0.2218536602370644
  (1113, 6257)	0.23954266132593235
  (1113, 6494)	0.1996273787759003
  (1113, 7361)	0.30158816908355374
  (1114, 1712)	0.48624980071695106
  (1114, 2083)	0.7752769557575491
  (1114, 3302)	0.4031212884158227

In [20]:
model=LogisticRegression()

In [21]:
#training the logistic regression with the training data
model.fit(X_train_feature,Y_train)

LogisticRegression()

In [22]:
print(X.shape,X_train.shape,X_test.shape)

(5572,) (4457,) (1115,)

**Feature Extraction**

In [23]:
#transform the text data to feature vectors that can be used as input to the logistic regression
feature_extraction=TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)

X_train_feature=feature_extraction.fit_transform(X_train)
X_test_feature=feature_extraction.transform(X_test)

#convert Y_train and Y_test values as integers
Y_train=Y_train.astype(int)
Y_test=Y_test.astype(int)

In [24]:
print(X_train_feature)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34678 stored elements and shape (4457, 7493)>
  Coords	Values
  (0, 2353)	0.28101404009316056
  (0, 3806)	0.28101404009316056
  (0, 1857)	0.17073786814794129
  (0, 1193)	0.22908400928709988
  (0, 3113)	0.28101404009316056
  (0, 3627)	0.25144905621529934
  (0, 6330)	0.24059246244542992
  (0, 1540)	0.17407870571957915
  (0, 2644)	0.28101404009316056
  (0, 5029)	0.17467075796896542
  (0, 4306)	0.26793132631329497
  (0, 421)	0.25144905621529934
  (0, 4557)	0.28101404009316056
  (0, 6468)	0.26793132631329497
  (0, 1657)	0.28101404009316056
  (0, 0)	0.23628394623676158
  (1, 3982)	0.4167622750027118
  (1, 5911)	0.2761926296686631
  (1, 3941)	0.20702870014136815
  (1, 1969)	0.1749293187718031
  (1, 6553)	0.4722950153731612
  (1, 5947)	0.24356944504246256
  (1, 3948)	0.2761926296686631
  (1, 2113)	0.1985161464110967
  (1, 3828)	0.13684128003316173
  :	:
  (4456, 5091)	0.1743505991070133
  (4456, 7339)	0.13767285254208542
  (4456, 2414)	0.17857780047236718
  (4456, 3262)	0.16745892210920407
  (4456, 7434)	0.1566807006510762
  (4456, 4120)	0.11213756070741854
  (4456, 3147)	0.11213756070741854
  (4456, 5430)	0.2902170940779003
  (4456, 3362)	0.13296028402451
  (4456, 1571)	0.1695693884304312
  (4456, 4975)	0.15534275099802256
  (4456, 1290)	0.1566807006510762
  (4456, 2236)	0.17068883072653956
  (4456, 2690)	0.19758564858135794
  (4456, 4765)	0.1730749026661772
  (4456, 5420)	0.19758564858135794
  (4456, 4878)	0.2137042449780485
  (4456, 5447)	0.2198234053076842
  (4456, 6646)	0.22771237505351186
  (4456, 6568)	0.23883125341667502
  (4456, 2138)	0.23883125341667502
  (4456, 3913)	0.23883125341667502
  (4456, 1186)	0.23883125341667502
  (4456, 877)	0.23883125341667502
  (4456, 7001)	0.23883125341667502

In [25]:
print(X_test_feature)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7823 stored elements and shape (1115, 7493)>
  Coords	Values
  (0, 893)	0.5968846858730686
  (0, 3659)	0.6647095420885805
  (0, 3748)	0.3001788854729708
  (0, 3982)	0.33433894948510406
  (1, 951)	0.40624130642412104
  (1, 3982)	0.2422352863555815
  (1, 4014)	0.4519692232535757
  (1, 4097)	0.25509897344874266
  (1, 6118)	0.4649108105460211
  (1, 6302)	0.4519692232535757
  (1, 7323)	0.29414309688485146
  (2, 726)	0.5784615622424353
  (2, 1511)	0.5054930834063402
  (2, 3302)	0.3286472702750399
  (2, 4290)	0.35146035376046975
  (2, 6707)	0.42228610575263104
  (3, 1403)	0.3190783090518022
  (3, 1535)	0.26860176862876095
  (3, 1628)	0.33607742717641215
  (3, 2121)	0.17912687495989912
  (3, 2613)	0.32672213738283684
  (3, 3101)	0.2806628348811889
  (3, 3170)	0.2806628348811889
  (3, 4856)	0.3481384934288401
  (3, 5424)	0.3651376115534502
  :	:
  (1111, 2767)	0.25490483698848077
  (1111, 5046)	0.39024262697465245
  (1111, 5357)	0.266009764263899
  (1111, 5618)	0.2999597919047991
  (1111, 6977)	0.1742576981016723
  (1111, 7190)	0.3720747354638948
  (1111, 7418)	0.2595045164597774
  (1112, 1869)	0.6693756697064054
  (1112, 3897)	0.5477089193614008
  (1112, 6679)	0.5019473602451435
  (1113, 1401)	0.5750952380611781
  (1113, 1683)	0.2635451401782607
  (1113, 2572)	0.24950459012529605
  (1113, 4055)	0.18267517691320964
  (1113, 4715)	0.2775856902312253
  (1113, 4994)	0.2698586179417211
  (1113, 5428)	0.28754761903058906
  (1113, 5697)	0.18498458298299114
  (1113, 5750)	0.2218536602370644
  (1113, 6257)	0.23954266132593235
  (1113, 6494)	0.1996273787759003
  (1113, 7361)	0.30158816908355374
  (1114, 1712)	0.48624980071695106
  (1114, 2083)	0.7752769557575491
  (1114, 3302)	0.4031212884158227

**Training the Model**

**Logistic Regression**

In [26]:
model=LogisticRegression()

In [27]:
#training the logistic regression with the training data
model.fit(X_train_feature,Y_train)

LogisticRegression()

**Evaluating on training data**

In [28]:
#prediction on training data

prediction_on_training_data=model.predict(X_train_feature)
accuracy_on_training_data=accuracy_score(Y_train,prediction_on_training_data)

In [29]:
print("Accuracy on training data :", accuracy_on_training_data)

Accuracy on training data : 0.9667938074938299

In [30]:
#prediction on test data

prediction_on_test_data=model.predict(X_test_feature)
accuracy_on_test_data=accuracy_score(Y_test,prediction_on_test_data)

In [31]:
print("Accuracy on test data :", accuracy_on_test_data)

Accuracy on test data : 0.9713004484304932

**Making a Predictive Model**

In [32]:
input_data=["I HAVE A DATE ON SUNDAY WITH WILL!!"]

#convert text to feature vectors
input_data_feature=feature_extraction.transform(input_data)

#making prediction
prediction=model.predict(input_data_feature)
print(prediction)

if prediction[0]==0:
  print("The mail is spam.")
else:
  print("The mail is not spam.")

[1]
The mail is not spam.